app:
  version: ""
  host: "inex.example.com"
  bot:
    path: "/bot"
    token: ""

telemetry:
  enabled: true
  envVars:
    {}
    # OTEL_METRICS_EXPORTER: prometheus
    # OTEL_EXPORTER_PROMETHEUS_HOST: "0.0.0.0"
    # OTEL_TRACES_EXPORTER: otlp

replicaCount: 1
image:
  repository: ghcr.io/modprobe/inex
  tag: latest

imagePullSecrets: []

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: inex.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: inex-cert
      hosts:
        - inex.example.com

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe: true
readinessProbe: true
