services:
  api:
    image: node:23
    working_dir: /app
    command: bash -c "corepack enable && pnpm install && pnpm run dev"
    volumes:
      - ".:/app"
      - "node_modules:/app/node_modules"
    ports:
      - "3000:3000"

volumes:
  node_modules: