apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inex.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inex.labels" . | nindent 4 }}
data:
  NODE_ENV: production
  APP_PORT: "3000"
  APP_HOST: {{ .Values.app.host | quote }}
  APP_BOT_PATH: {{ .Values.app.bot.path | quote }}

  {{- if .Values.app.version }}
  APP_VERSION: {{ .Values.app.version | quote }}
  {{- end }}

  {{- if (and .Values.telemetry.enabled .Values.telemetry.envVars) }}
  {{ .Values.telemetry.envVars | toYaml | nindent 2 }}
  {{- end }}

  DEBUG: "telegraf:*"