apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inex.fullname" . }}
  labels:
    {{- include "inex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "inex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "inex.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ if (eq .Values.image.tag "latest") }}Always{{ else }}IfNotPresent{{ end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
            {{- if (and .Values.telemetry.enabled .Values.telemetry.envVars.OTEL_METRICS_EXPORTER (eq .Values.telemetry.envVars.OTEL_METRICS_EXPORTER "prometheus")) }}
            - name: metrics
              containerPort: {{ int (default "9464" .Values.telemetry.envVars.OTEL_EXPORTER_PROMETHEUS_PORT) }}
              protocol: TCP
            {{- end }}
          env:
            - name: PORT
              value: "3000"
            {{- if .Values.appVersion }}
            - name: APP_VERSION
              value: {{ .Values.appVersion | quote }}
            {{- end }}
            {{- if .Values.telemetry.enabled }}
            {{- range $k, $v := .Values.telemetry.envVars }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
