apiVersion: v1
kind: Secret

metadata:
  name: {{ include "inex.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inex.labels" . | nindent 4 }}

type: Opaque
data:
  APP_BOT_TOKEN: {{ .Values.app.bot.token | quote | b64enc }}