apiVersion: v1
kind: Service
metadata:
  name: {{ include "inex.fullname" . }}
  labels: {{- include "inex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- $telemetryEnabled := .Values.telemetry.enabled -}}
    {{- $prometheusExporterUsed := (and .Values.telemetry.envVars.OTEL_METRICS_EXPORTER (eq .Values.telemetry.envVars.OTEL_METRICS_EXPORTER "prometheus")) -}}
    {{- if (and $telemetryEnabled $prometheusExporterUsed) }}
    - port: {{ int (default "9464" .Values.telemetry.envVars.OTEL_EXPORTER_PROMETHEUS_PORT) }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector: {{- include "inex.selectorLabels" . | nindent 4 }}
