name: Production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE: ghcr.io/modprobe/inex

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: build
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .

          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - build
    concurrency:
      group: deploy-production
      cancel-in-progress: false
    env:
      NAMESPACE: inex
      HOSTNAME: inex.t8n.io
      REPLICAS: "3"
      IMAGE_PULL_SECRET_NAME: ghcr-pullsecret
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
      - uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: |-
            helm upgrade production ./chart \
              --install \
              --wait \
              --atomic \
              --namespace=${{ env.NAMESPACE }} \
              --create-namespace \
              --set replicaCount=${{ env.REPLICAS }} \
              --set-string appVersion=${{ github.sha }} \
              --set-string image.repository=${{ env.IMAGE }} \
              --set-string image.tag=${{ github.sha }} \
              --set-json imagePullSecrets='[{"name": "${{ env.IMAGE_PULL_SECRET_NAME }}" }]' \
              --set-json ingress.hosts='[{ "host": "${{ env.HOSTNAME }}", "paths": [{ "path": "/", "pathType": "ImplementationSpecific" }] }]' \
              --set-json ingress.tls='[{ "secretName": "inex-prod-cert", "hosts": ["${{ env.HOSTNAME }}"]}]' \
              --set-string ingress.annotations."cert-manager\.io/cluster-issuer"=letsencrypt-prod \
              --set-string resources.requests.cpu=100m,resources.requests.memory=128Mi \
              --set-string resources.limits.cpu=150m,resources.limits.memory=192Mi
            
